name: Install Tests

# CINTENT >> MANUAL_TRIGGER
# on:
#   pull_request:
#     types: [opened, synchronize]
#   push:
#     branches:
#       - main
on: [repository_dispatch, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install:
    name: ${{ matrix.python_version }} install
    strategy:
      fail-fast: true
      matrix:
        # CINTENT >> REMOVE_MATRIX
        # python_version: ["3.8", "3.13"]
        python_version: ["3.13"]
    runs-on: ubuntu-latest
    steps:
      - name: Set up python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - uses: actions/checkout@v4
      
      # CINTENT >> INSERT_CINTENT
      - uses: JavidDitty/setup-cintent@3e5b2faf83a2ad32c22a1cd0f86f5f20ea53a5ab

      - name: Build package
        run: |
          make package

      - name: Install package
        run: |
          python -m pip install "unpacked_sdist/."

      - name: Test by importing packages
        run: |
          python -c "import sdmetrics"

      - name: Check package conflicts
        run: |
          python -m pip check

      # CINTENT >> INSERT_CINTENT
      - name: Upload CIntent Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.CINTENT_ARTIFACT_NAME }}
          path: ${{ env.CINTENT_LOGS }}
